# Generated by Django 4.1.7 on 2023-04-20 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=255)),
                ('is_done', models.BooleanField(default=False, help_text='temp text')),
                ('time', models.TimeField(blank=True, null=True)),
                ('priority', models.IntegerField()),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, choices=[('H', 'Home'), ('W', 'Work')], max_length=1)),
            ],
            options={
                'verbose_name': 'note',
                'verbose_name_plural': 'note',
            },
        ),
        migrations.CreateModel(
            name='SubNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField()),
                ('text', models.TextField()),
                ('estimated_time', models.IntegerField(blank=True, null=True)),
                ('spent_time', models.IntegerField(blank=True, null=True)),
                ('from_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subnotes', to='notes.note', verbose_name='From note')),
            ],
            options={
                'verbose_name': 'subnote',
            },
        ),
    ]
