# Generated by Django 4.1.7 on 2023-03-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_done', models.BooleanField()),
                ('time', models.TimeField()),
                ('priority', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Note',
            },
        ),
    ]
