# Generated by Django 4.1.7 on 2023-04-20 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AddConstraint(
            model_name='subnote',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('is_done', True), ('spent_time__isnull', False)), models.Q(('is_done', False), ('spent_time__isnull', True)), _connector='OR'), name='subnote_spent_time_error', violation_error_message="Can't be done without spent_time"),
        ),
    ]
