# Generated by Django 4.1.7 on 2023-03-30 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='is_done',
            field=models.BooleanField(default=False, help_text='temp text'),
        ),
        migrations.AlterField(
            model_name='note',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
