# Generated by Django 4.1.7 on 2023-04-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_is_done_alter_note_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='done_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
