# Generated by Django 4.1.7 on 2023-04-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_done_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
