# Generated by Django 4.1.7 on 2023-04-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_note_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'all current subnotes',
            },
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'all current notes', 'verbose_name_plural': 'notes'},
        ),
        migrations.AddField(
            model_name='note',
            name='location',
            field=models.CharField(blank=True, choices=[('H', 'Home'), ('W', 'Work')], max_length=1),
        ),
    ]
