# Generated by Django 4.1.7 on 2023-04-11 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_note_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'note', 'verbose_name_plural': 'note'},
        ),
        migrations.AddField(
            model_name='note',
            name='location',
            field=models.CharField(blank=True, choices=[('H', 'Home'), ('W', 'Work')], max_length=1),
        ),
        migrations.CreateModel(
            name='SubNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField()),
                ('text', models.TextField()),
                ('from_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.note', verbose_name='From note')),
            ],
            options={
                'verbose_name': 'subnote',
            },
        ),
    ]
