# Generated by Django 4.1.7 on 2023-04-11 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_alter_note_options_note_location_subnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subnote',
            name='from_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subnotes', to='notes.note', verbose_name='From note'),
        ),
    ]
