# Generated by Django 4.1.7 on 2023-04-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_alter_subnote_from_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='subnote',
            name='estimated_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='subnote',
            name='spent_time',
            field=models.IntegerField(null=True),
        ),
    ]
