# Generated by Django 4.1.7 on 2023-04-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_subnote_estimated_time_subnote_spent_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subnote',
            name='estimated_time',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='subnote',
            name='spent_time',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
