# Generated by Django 4.1.7 on 2023-04-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_alter_subnote_estimated_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subnote',
            name='estimated_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subnote',
            name='spent_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
