# Generated by Django 4.1.7 on 2023-04-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_alter_subnote_estimated_time_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subnote',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('is_done', True), ('spent_time__isnull', False)), models.Q(('is_done', False), ('spent_time__isnull', True)), _connector='OR'), name='subnote_spent_time_error'),
        ),
    ]
