# Generated by Django 4.1.7 on 2023-04-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_subnote_subnote_spent_time_error'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subnote',
            name='subnote_spent_time_error',
        ),
        migrations.AddConstraint(
            model_name='subnote',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('is_done', True), ('spent_time__isnull', False)), models.Q(('is_done', False), ('spent_time__isnull', True)), _connector='OR'), name='subnote_spent_time_error', violation_error_message="Can't be done without spent_time"),
        ),
    ]
